apiVersion: v1
kind: Service
metadata:
  name: fastfood-pedido
  namespace: fastfood
spec:
  type: NodePort
  selector:
    app: fastfood-pedido
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31003