version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: postgres_dev_network_pedidos
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_pedidos:/var/lib/postgresql/data
    networks:
      - postgres_dev_network
volumes:
  postgres_data_pedidos:

networks:
  postgres_dev_network: